###Script to compare the species richness generated by my simulation
#to those predicted by Ryan Chisholm's model
rm(list=ls())
graphics.off()

#install nlls fitting package
#install.packages("minpack.lm") <- if you've never installed minpack before
library("minpack.lm") #for nlls fitting

#Read in our simulation data
SimData <- read.csv("../../Results/SimModelFitData.csv")

#define the function
chisholm_model <- function(area, theta, m0, K) {
  rho = 1
  K = K
  Js = area*rho
  J_stars = Js/K
  ms = m0/sqrt(area)
  gamma_stars = J_stars*ms/(1-ms)
  return(theta*(digamma(theta/K+gamma_stars*(digamma(gamma_stars+J_stars)-digamma(gamma_stars)))-digamma(theta/K)))
}

#for each simulation define values for species_richness, area, migration rate, number of niches

results_list <- list()
points_list <- list()

for (i in 1:length(unique(SimData$sim_number))) {  #for each unique simulation
  
  islands <- SimData[SimData$sim_number == i, ] #isolate the data from that sim of islands
  
  #for the nlls model fitting we'll just use the known island areas and sp richness
  #then we'll see if A) the model fits successfully and 
  #B) if the estimated parameters for K and m0 match what we KNOW for the islands
  
  
  #How will the NLLS fitting give me accurate results if each island in the dataset has
  #a different m rate and number of niches
  #should I subset islands by m rate and niches and see if the model can tell me what they are?
  
  x <- SimData[SimData$migration_rates == 0.001, ]
  y <- x[x$K_num == 1, ]
  
  
  # first we need some starting parameters for the model
  theta_start <- nu*(area-1)/(1-nu)
  m0_start <- 0.2 
  K_start <- 20 
  
  fit_chisholm <- try(nlsLM(species_richness ~ chisholm_model(area = area, theta, m0, K), islands,
                        list(theta=theta_start, m0 = m0_start, K = K_start)), silent=T)
  
  summary(fit_chisholm)
  
  
  #Calculate the sum of squared errors - if there was no error in the model fitting!
  if(class(fit_chisholm) != "try-error"){
    RSS <- sum(residuals(fit_chisholm)^2) #Residual sum of squares of our NLLS model
    TSS <- sum((species_richness - mean(species_richness))^2) #Total sum of squares 
    RSq <- 1 - (RSS/TSS) #R-squared value
    
    # plot it:
    area <- islands$area
    
    chisholm_points <- chisholm_model(area = area, theta = coef(fit_chisholm)["theta"], m0 = coef(fit_chisholm)["m0"], K = coef(fit_chisholm)["K"])
    df1 <- data.frame(area, chisholm_points)
    df1$Model <- "Chisholm Model"
    names(df1) <- c("Area", "Sp_Rich", "Model")
    
    #store the r-Squared results
    #store these results
    results <- data.frame(i, RSq, coef(fit_chisholm)["theta"], coef(fit_chisholm)["m0"], coef(fit_chisholm)["K"])
    names(results) <- c("Sim_Num", "R-Squared", "EstTheta", "EstMigration", "EstNiches")
    
  
  } else {
    results <- data.frame(i, NA, NA, NA, NA)
    names(results) <- c("Sim_Num", "R-Squared", "EstTheta", "EstMigration", "EstNiches")

    df1 <- data.frame(NA, NA)
    df1$Model <- "Chisholm Model"
    names(df1) <- c("Area", "Sp_Rich", "Model")
  }
  
  results_list[[i]] <- results
  points_list[[i]] <- df1
  }  

final_results <- do.call(rbind,results_list)
final_results <- as.data.frame(final_results)
final_results$`R-Squared` <- round(final_results$`R-Squared`, digits = 2)
final_results$EstTheta <- round(final_results$EstTheta, digits = 2)
final_results$EstMigration <- round(final_results$EstMigration, digits = 2)
write.csv(final_results, "../../Results/NllsSimResults010620.csv", row.names = FALSE)
  
