###Script to compare the species richness generated by my simulation
#to those predicted by Ryan Chisholm's model
#Also statistical analysis of my simulation data 

rm(list=ls())
graphics.off()

#package for finding the mode
#install.packages("modeest")
library("modeest")
library("ggplot2")
library("dplyr")

#Find import the results of the simulation
SimData <- read.csv("../../Results/SimModelFitData.csv")

#define the model function
chisholm_model <- function(area, theta, m0, K) {
  rho = 1
  K = K
  Js = area*rho
  J_stars = Js/K
  ms = m0/sqrt(area)
  gamma_stars = J_stars*ms/(1-ms)
  return(theta*(digamma(theta/K+gamma_stars*(digamma(gamma_stars+J_stars)-digamma(gamma_stars)))-digamma(theta/K)))
}

#function to compare total results to model
compare_total_results <- function() {
  
  #create empty list for storing estimated species richness
  island_species <- vector()
  
  EstData <- SimData[ ,1:4]
  
  for (i in 1: nrow(EstData)) {
    data <- EstData[i, ]
    m = data$migration_rate
    area = data$area
    J = area
    m0 = m*sqrt(area)
    nu = 0.001
    theta = 2*J*nu
    K = data$K_num
    island_species[[i]] <- round(chisholm_model(area, theta, m0, K), digits = 2)
  }
  
  #bind results to single dataframe
  EstData <- cbind.data.frame(EstData, island_species)
  
  return(EstData)
  
}

bind_my_dfs <- function() {
  
  SimOrModel <- rep("Chisholm_Model", nrow(EstData))
  EstData <- cbind.data.frame(EstData, SimOrModel)
  SimOrModel <- rep("Solman_Sim", nrow(SimData))
  SimData <- cbind.data.frame(SimData, SimOrModel)
  TotalData <- rbind.data.frame(SimData, EstData)
  
  return(TotalData)
}

###RUN THE MODEL AND GET OUR ESTIMATES
EstData <- compare_total_results()
TotalData <- bind_my_dfs()
TotalData2 <- cbind.data.frame(SimData, EstData$island_species)

###CHECK TO SEE IF THE DATA ARE NORMALLY DISTRIBUTED
#Let's check to see if our data is normally distributed
hist(SimData$island_species) #produces left skewed data
hist(EstData$island_species) #produces uniform frequency of observations, no 'hump'

mean(SimData$island_species) #9.39
median(SimData$island_species) #9
mlv(SimData$island_species) #11 - mode
mean(EstData$island_species) #10.60
median(EstData$island_species) #10.72
mlv(EstData$island_species) #5.56 - mode

#So my dataset appears to be fairly normally distributed, 
#but the model estimations are not

###Range, variance and standard deviation
range(SimData$island_species) # 1 - 33
range(EstData$island_species) # 1 - 20.88

#Variance is the deviation from the mean of each datapoint,
#squared then divided by the number of datapoints
#minus one
var(SimData$island_species) #23.11
var(EstData$island_species) # 33.94

#if we square root the variance we get the standard deviation
sqrt(var(SimData$island_species)) #4.81
sd(SimData$island_species) #4.81
sqrt(var(EstData$island_species)) # 5.83
sd(EstData$island_species) #5.83

###LETS Z TRANSFORM THE DATA
#This standardizes the data to a mean of 0 and SD of 1
#we do this by dividing the deviations from the mean, by the 
#standard deviation

zSimData <- (SimData$island_species - mean(SimData$island_species))/sd(SimData$island_species)
var(zSimData) #variance of 1
sd(zSimData) #SD of 1
hist(zSimData) #still left skewed but more normally distributed
summary(zSimData)

####LETS MAKE A BOX PLOT OF SIMULATED AND ESTIMATED SPECIES RICHNESSES
boxplot(TotalData$island_species ~ TotalData$SimOrModel, col = c("red", "blue"), ylab = "Num_Species")
#This boxplot shows that the simulation median is lower than the estimated
#median. The interquartile range of the simulation is smaller than the model estimation.
#The lower quartiles (25% of values fall below the lower quartile line)
#are similar, but the model upper quartile (75% of scores fall below the upper quartile value)
#is higher. Whilst the minimum values are similar, the simulation had higher maximum values.
#The upper whisker (whiskers represent scores outside the middle 50%) is larger for the simulation, 
#but the lower whiskers are similar.

# #subset islands by migration rate/niches
# #function to subset data by migration rate/number of niches
# 

####LETS LOOK AT THE STANDARD ERRORS OF OUR DATA
#Standard errors are a good way to display uncertainty
seSim <- sqrt(var(SimData$island_species)/length(SimData$island_species))
# 0.00537

seEst <- sqrt(var(EstData$island_species)/length(EstData$island_species))
# 0.00651

#As both datasets have the same number of datapoints we can see 
#that the simulation has a lower standard error than the model estimation

#######LET'S DO A HYPOTHESIS TEST TO SEE IF THESE DIFFERENCES MEAN SOMETHING
#Null hypothesis: The difference between simulation species richness and model species 
#richness is zero

#Usually t-test should only be done on normally distributed data
#but because we have a large dataset (N>50) we can use it

t.test1 <- t.test(TotalData$island_species ~ TotalData$SimOrModel)
t.test1
# t = -144.34, df = 1544310, p value < 0.05
#reject null hypothesis, accept alternative hypothesis, the true difference in means
#is not equal to zero
#95% CI -1.2355 -1.2024 - 95% of the differences in species number is between -1.20 and -1.24
#with model having more species
#mean in group Solman_Sim 9.39
#mean in group Chisholm Model 10.61

###LET'S USE A LINEAR MODEL TO SEE IF THERE IS A RELATIONSHIP BETWEEN
#ISLAND AREA AND NUMBER OF SPECIES IN MY SIMULATION

model1 <- lm(island_species ~ area, data = SimData)
summary(model1)
#model summary give us parameter estimates, stand errors,
#t-values, p-values, the intercept and the slope for area.

# Call:
#   lm(formula = island_species ~ area, data = SimData)
# 
# Residuals:
#   Min       1Q   Median       3Q      Max 
# -14.2633  -2.4808  -0.3219   2.1671  14.0986 
# 
# Coefficients:
#   Estimate Std. Error t value Pr(>|t|)    
# (Intercept) 5.129e+00  5.665e-03   905.3   <2e-16 ***
#   area        3.863e-02  3.948e-05   978.5   <2e-16 ***
#   ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Residual standard error: 3.244 on 799998 degrees of freedom
# Multiple R-squared:  0.5448,	Adjusted R-squared:  0.5448 
# F-statistic: 9.574e+05 on 1 and 799998 DF,  p-value: < 2.2e-16

#from this was can infer: 
#The data for the intercept is statistically significantly different from zero
#but we're not interested in the number of species on an island with 0 area
#most of the time in statistics the intercept isn't very interesting
#if we z-standardise the area the intercept will become significant - 
#it would give us the mean species richness.
#The slope statistic is statistically significantly different from zero 
#with p < 0.001. 
#we can also see that for every 1 unit increase in area, there is a 0.04 increase 
#in number of species
#There are also 799998 degrees of freedom because there are 8000000 observations
#minus 2 parameters. In statistics, the number of degrees of freedom is the number 
#of values in the final calculation of a statistic that are free to vary.
#R-squared value is 0.5448 - that tells us that 54% of variation in number of species
#on an island is explained by variation in area. 
hist(model1$residuals)
head(model1$residuals)

#Now let's run the model with the covariate (the continuous predictor variable - area)
#z-standardized
SimData$z.area <- scale(SimData$area)
model2 <- lm(island_species ~ z.area, data = SimData)
summary(model2)

#This model fitting give us the same R-squared value and same p-values
#but this time the estimated intercept value is actually our mean species richness across all islands

#LET'S USE A T-TEST TO TEST OUR LINEAR MODEL
model3 <- lm(island_species~SimOrModel, data = TotalData)
test3 <- t.test(TotalData$island_species~TotalData$SimOrModel, var.equal=TRUE)
summary(model3)
test3

###Let's also try a paired sample t-test
test4 <- t.test(TotalData2$island_species, TotalData2$`EstData$island_species`, paired = TRUE, alternative = "two.sided")
test4 #shows there is a statistically significant difference between the paired data points
#with mean of difference -1.2 - there's a mean of 1.2 additional species from the model estimates

#We need to do some linear model diagnostics to make sure the 
#assumptions one makes for a linear model are met
#The most important assumption of linear models is that the residuals 
#are normally distributed
#We can only test for that after we've fit the model becuase that's how
#we get our residuals

#par(mfrow=c(2,2))
#plot(model2) #when I try and plot the residuals for my
#simulation z.transformed area/sp rich linear model
#r studio crashes. I think this is because the data set is too big.
#I will subset the data, re-run the model, then plot the residuals

model4 <- lm(island_species ~ z.area, data = SimData[SimData$sim_number == 1, ])
par(mfrow=c(2,2))
plot(model4)

#The top left plot shows the residuals (distances between
#the values and the calculated regression line), again the fitted values. 
#These appear to be distributed roughly randomly.
#The plot in the top right hand corner 
#gives the standardized residuals plotted against the quantiles 
#they are supposed to fall into, assuming they are normally distributed.
#The line is fairly straigh so we're happy with this result.

##EXAMPLE OF REPORTING RESULTS###
#Method
#To test whether larger islands also had greater species richness, I used a linear
#model, where species richness was the response variable and island area the explanatory variable.
#I z-standardised island area to a mean of 0 and SD of one, so that the intercept could
#be interpreted as the mean of species richness.
#Following the analysis, I used visual inspection of residual plots to assess that the assumption 
#that the residuals follow a normal distribution was not violated.
#I report results as statistically significant if p equals or is smaller than 0.05. 
#I used R version 3.3 (R Core Team 2015) for all analysis and plotting.

#Results
#I used data from 800000 simulated islands. The mean species richness was 9 (SD 4.81, range: 1-33).
#The mean area of islands was (SD , range). I found a positive, statistically significant association 
#between species richness and island area (Table 1 - inc intercept and area parameter est, with z-standardised area,
# as well as SE for each and t values and p values).
#An increase in 1SD unit area meant an increase of 3.55 species

#####LET'S PLAY WITH ANOVAS
#ANOVAs test for differences between groups
#if we go back to the linear model where we looked at the 
#difference in species richness on islands as generated by the simulation
#and the model, we can see that an ANOVA has already
#been performed and we can access the data

anova(model3)
# Analysis of Variance Table
# 
# Response: island_species
# Df   Sum Sq Mean Sq F value    Pr(>F)    
# SimOrModel       1   594359  594359   20833 < 2.2e-16 ***
#   Residuals  1599998 45648251      29                      
# ---
#   Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#So we have the sum of squares of the between group variance (594359)
#and those for the residuals (45648251).
#Then there are the mean squares for each of these two (within -29- and 
#between - 594359 - group)
#The F-value (20833) is calculated by dividing the mean squares of the between-group 
#estimate by the residual mean squares
#The p-value < 0.001 shows us that species richness does differ
#between the simulation and model predictions.
#But how much does it differ? 
#To find this out we do a t-test like we did before Such a test
#that one runs after the main analysis, to see which group differs, and how much
#it differs from another group, are called post-hoc tests.
test3 #high t value (-144.34), large df, low p-value - there is a statistical difference!

#ANOVA test whether variation within groups is smaller than variation amoung groups
#Why don't we run an ANOVA and then a linear model, with species richness as response
#and number of niches as factorial explanatory factor.
#let's start with a boxplot
boxplot(SimData$island_species~SimData$K_num, ylab = "Species Richness")
count(SimData, K_num) #each number of niches occurs 40,000 times

model4 <- lm(island_species ~ as.factor(K_num), data = SimData)
anova(model4) #this shows us that there is statistically significantly more variation
#amoung niche groups than within-groups (residuals).
#Here the difference between an ANOVA and a t.test is that a t.test
#is about estimates, about the difference in size. ANOVA is about the difference
#in variance among groups vs within groups.

#But here we have 20 niche factors, we don't want to do post hoc t-test on
#all of them. Instead we can do...
summary(model4)
#this gives us the summary of our linear model, but this time with 
#a factorial explanatory factor, instead of continuous explanatory variable
#(or covariate - area) or with a two level variable (sim or model)

#So in the intercept row we get the values for the 1 niche factor
#it estimates 1.311 species for one niche
#all values there after are what we would add/subtracked from the first row!
#so estimates species for k_num 20 = 1.3 + 14.21

###NOW LET'S LOOK AT REPEATABILITY
#Let's find out if the simulation method is of a high quality
#We want to look at the repeatability or "intraclass correlation coefficient"
#of our simulation
#repeatability = among group variable squared, divides by within group variable 
#plus amoung-group vairance
#we calculate the fraction of the variance of the total variance that is explained by
#among group differences
#we have equal sample sizes amoung our simulations so I don't need to calculate n0.
model5 <- lm(island_species ~ as.factor(sim_number), data = SimData)
anova(model5)
repeatability = (4082.5-22.6)/(22.6+(4082.5-22.6)) #my simulation has 99% repeatability - it is a quality method!
#99% of variation in species richness is determined by between simulation differences.
#That equally means that simulations are consistent in their species richness
#The concept for repeatability is an important one

####LET'S LOOK AT FITTING MODELS IN R THAT USE MULTIPLE VARIABLES TO EXPLAIN THE RESPONSE VARIABLE
##Homogeneity of variances
#This is an important assumption for ANOVAS and regression
#analysis in general.
#To run the model explaining species richness with area and 
#number of niches we have to assume that the variances within each area and
#niche number are similar. 
#A rule of thumb for ANOVA is that the ratio between the largest
#and smallest variance should not be much more than 4.

par(mfrow = c(1, 2))
plot(island_species ~ area, data = SimData) #this doesn't work as there's too many areas
plot(island_species ~ K_num, data = SimData)

SimData %>%
  group_by(area) %>%
  summarise (variance=var(island_species))

SimData %>%
  group_by(K_num) %>%
  summarise (variance=var(island_species))

#The ratio of differences between areas and K_nums are too high!
#It is inappropriate to try and run a model explaining species_richness
#with area and number of niches

#Let's try using multiple regression to see if both number of niches and
#island area are important for predicting number of species 
#We'll use the built in pairs() function to look at the distribution of the data
#This generates a neat layout from a dataframe that plots each variable
#against each other variable in the dataframe
summary(SimData)
sim1 <- SimData[SimData$sim_number == 1, ]
par(mfrow = c(2,2))
boxplot(sim1$island_species)
boxplot(sim1$area)
boxplot(sim1$K_num)

var(SimData$island_species) #23.11
var(SimData$area) #8437.198
var(SimData$K_num) #33.25

#The variances for these are large, not v homogenous!
#What we can do is standardize out xs for the analysis
SimData$z.K_num <- scale(SimData$K_num)
var(SimData$z.K_num) # 1!
sim1 <- SimData[SimData$sim_number == 1, ]
plot(sim1) #analysis with the z-scores looks a little more normal than without

#Are the data normally distributed? - Not great but it'll do
#Are there excessively many zeros? There are quite as few,
#but we'll go with it at this point
sim1 <- sim1[, 5:7]

par(mfrow = c(2,2))
hist(sim1$island_species)
hist(sim1$z.area)
hist(sim1$z.K_num)

pairs(sim1) #is there colinearity amoung covariates?
cor(sim1)
#These variables are all positively correlated, with
#number of niches being a better predictor of species richness 
#than island area.
#Too much correlation amoung the predictors (niche number and area)
#is not a good thing. This is called collinearity. What it does is it inflates
#variation. So when you have a lot of collinearity in your covariates,
#You'll get larger standard errors of those correlated variables
#than you'd get if there was no collinearity.
#This means it is more difficult to detect an effect, that you are likely 
#to not get a significant result even though there might be one. 
#This means that if there is lost of collinearity any normal evaluation of a model is super conservative.

#Also, dropping covariates can affect the stimates of other
#covariates if there is collinearity around. That can be super confusing.
#The standard errprs are inflated with the square rootof the Variance Inflation Factor. 
#This VIF we can use to find out what amount of collinearity is too much.
#VIF can be calulated by running an extra linear model in which the covariate of focus (here, K_num)
#is y and all other covariates of the model (here only area)
#are covariates. Then you can calculate the VIF as follows.

summary(lm(z.K_num ~ z.area, data = sim1))
VIF <- 1/(1-0.43) #0.43 is the nultiple r squared value
VIF
sqrt(VIF) #The standard errors of k_num are thus inflated by
# 1.32 which is not a lot. A VIF of 1.8 is also okay. 
#Keep it in mind when you do oyur interpretation and discolse it in your report!
#think biology always!

### remember:
#visually inspect relationships
#consider interactions

#if k_num has such a high correlation with species richness, do we actually need both variables?
simMod <- lm(island_species ~ z.K_num + z.area, data = sim1)
anova(simMod)
#this shows we need area and niche number to predict sp richness

#if we look at the coefficients in the linear model summary, then we
#can get estimates of the slopes and intercept
summary(simMod)
#Looking at Rsquared more than 86% of the variance in
#species richness is explaine by species = 10.07 + 3.51 * z.K_num + 1.64 * z.area

#time for model validation
plot(simMod) #error margins too large, need to reduce the dataset

#CHECK LIST OF STATISTICAL ANALYSIS AND MODEL FITTING
# 1: Outliers 
# 2: Homogeneitry of variances 
# 3: Are the data normally distributed?
# 4: Are there excessively many zeroes?
# 5: Is there collinearity among the covariates?
# 6: Visually inspect relationships 
# 7: Consider interactions?
# 8: Decide on maximal model based on biology and question 
# 9: Simplify model 
# 10: Decide on final model 
# 11: Run model validation