###Script to compare the species richness generated by my simulation
#to those predicted by Ryan Chisholm's model
rm(list=ls())
graphics.off()

#install nlls fitting package
#install.packages("minpack.lm") <- if you've never installed minpack before
library("minpack.lm") #for nlls fitting

#Read in our simulation data
SimData <- read.csv("../../Results/SimModelFitData.csv")

#define the function
chisholm_model <- function(area, theta, m0, K) {
  rho = 1
  K = K
  Js = area*rho
  J_stars = Js/K
  ms = m0/sqrt(area)
  gamma_stars = J_stars*ms/(1-ms)
  return(theta*(digamma(theta/K+gamma_stars*(digamma(gamma_stars+J_stars)-digamma(gamma_stars)))-digamma(theta/K)))
}


#run model fitting for one migration rate

data <- SimData[SimData$migration_rates == 0.05, ]

results_list <- list()

for (i in 1:length(unique(data$sim_number))) {
  
  #get a dataset where the migration rates are the same
  
  new_data <- data[data$sim_number == i, ]
  
  area <- new_data[3] #assign the area column of our dataframe to a vector
  species_rich <- new_data[5] #assign the species richness column of our dataframe to a vector
  new_data <- data.frame(area, species_rich) 
  names(new_data) <- c("area", "species_rich") #rename the columns
  new_data$area <- as.numeric(as.character(new_data$area)) #
  
  theta_start <- nu*(new_data$area-1)/(1-nu)
  
  fit_chisholm <- try(nlsLM(species_rich ~ chisholm_model(area, theta, m0, K), data = new_data, start = list(theta = 10, m0 = 0.5, K=10)), silent=T)
  
  summary(fit_chisholm)
  
  
  #Calculate the sum of squared errors - if there was no error in the model fitting!
  if(class(fit_chisholm) != "try-error"){
    RSS <- sum(residuals(fit_chisholm)^2) #Residual sum of squares of our NLLS model
    TSS <- sum((data$species_rich - mean(data$species_rich))^2) #Total sum of squares 
    RSq <- 1 - (RSS/TSS) #R-squared value
    
    # plot it:
    area <- new_data$area
    
    chisholm_points <- chisholm_model(area = area, theta = coef(fit_chisholm)["theta"], m0 = coef(fit_chisholm)["m0"], K = coef(fit_chisholm)["K"])
    df1 <- data.frame(area, chisholm_points)
    df1$Model <- "Chisholm Model"
    names(df1) <- c("Area", "Sp_Rich", "Model")
    
    #store the r-Squared results
    #store these results
    results <- data.frame(i, RSq, coef(fit_chisholm)["theta"], coef(fit_chisholm)["m0"], coef(fit_chisholm)["K"])
    names(results) <- c("Sim_Num", "R-Squared", "EstTheta", "EstMigration", "EstNiches")
    
    
  } else {
    results <- data.frame(i, NA, NA, NA, NA)
    names(results) <- c("Sim_Num", "R-Squared", "EstTheta", "EstMigration", "EstNiches")
    
    df1 <- data.frame(NA, NA)
    df1$Model <- "Chisholm Model"
    names(df1) <- c("Area", "Sp_Rich", "Model")
  }
  
  results_list[[i]] <- results
  
}

#get a dataset where the migration rates are the same

new_data <- data[data$sim_number == i, ]

area <- data[3] #assign the area column of our dataframe to a vector
species_rich <- data[5] #assign the species richness column of our dataframe to a vector
data <- data.frame(area, species_rich) 
names(data) <- c("area", "species_rich") #rename the columns
data$area <- as.numeric(as.character(data$area)) #
  
  # first we need some starting parameters for the model
  nu = 0.001
  theta_start <- nu*(data$area-1)/(1-nu)
  m0_start <- 0.05*sqrt(data$area)
  island_species <- data$island_species
  area <- data$area
  
  fit_chisholm <- try(nlsLM(species_rich ~ chisholm_model(area, theta, m0, K), data = data, start = list(theta = theta_start, m0 = 0.05, K=10)), silent=T)
  
  summary(fit_chisholm)
  
  
  #Calculate the sum of squared errors - if there was no error in the model fitting!
  if(class(fit_chisholm) != "try-error"){
    RSS <- sum(residuals(fit_chisholm)^2) #Residual sum of squares of our NLLS model
    TSS <- sum((data$species_rich - mean(data$species_rich))^2) #Total sum of squares 
    RSq <- 1 - (RSS/TSS) #R-squared value
    
    # plot it:
    area <- data$area
    
    chisholm_points <- chisholm_model(area = area, theta = coef(fit_chisholm)["theta"], m0 = coef(fit_chisholm)["m0"], K = coef(fit_chisholm)["K"])
    df1 <- data.frame(area, chisholm_points)
    df1$Model <- "Chisholm Model"
    names(df1) <- c("Area", "Sp_Rich", "Model")
    
    #store the r-Squared results
    #store these results
    results <- data.frame(i, RSq, coef(fit_chisholm)["theta"], coef(fit_chisholm)["m0"], coef(fit_chisholm)["K"])
    names(results) <- c("Sim_Num", "R-Squared", "EstTheta", "EstMigration", "EstNiches")
    
  
  } else {
    results <- data.frame(i, NA, NA, NA, NA)
    names(results) <- c("Sim_Num", "R-Squared", "EstTheta", "EstMigration", "EstNiches")

    df1 <- data.frame(NA, NA)
    df1$Model <- "Chisholm Model"
    names(df1) <- c("Area", "Sp_Rich", "Model")
  }
  
  results_list[[i]] <- results
  points_list[[i]] <- df1
  }  

final_results <- do.call(rbind,results_list)
final_results <- as.data.frame(final_results)
final_results$`R-Squared` <- round(final_results$`R-Squared`, digits = 2)
final_results$EstTheta <- round(final_results$EstTheta, digits = 2)
final_results$EstMigration <- round(final_results$EstMigration, digits = 2)
write.csv(final_results, "../../Results/NllsSimResults010620.csv", row.names = FALSE)
  
