###Script to compare the species richness generated by my simulation
#to those predicted by Ryan Chisholm's model
rm(list=ls())
graphics.off()
library("ggplot2")

#Find import the results of the simulation
simulation_data <- read.csv("../../Results/SimResults010620.csv")

#find mean of results and add to dataframe
meanie <- function() {
  for (m in 1:length(unique(simulation_data$m0))) {
    df <- simulation_data[simulation_data$m0 == m*2/1000, ]
    mean <- mean(df$sp_rich)
    x <- df[1, ]
    x$sp_rich <- mean
    x$simulation <- 101
    simulation_data[2000 + m, ] <- x
  }
  return(simulation_data)
}

simulation_data <- meanie()

#define the model function
chisholm_model <- function(area, theta, m0, K) {
  rho = 1
  K = K
  Js = area*rho
  J_stars = Js/K
  ms = m0/sqrt(area)
  gamma_stars = J_stars*ms/(1-ms)
  return(theta*(digamma(theta/K+gamma_stars*(digamma(gamma_stars+J_stars)-digamma(gamma_stars)))-digamma(theta/K)))
}

#create empty list for storing estimated species richness
estimated_sp_rich <- vector()

for (i in 1:nrow(simulation_data)) {
  m = simulation_data[i, ]$m
  area = m*10000
  m0 = simulation_data[i, ]$m*sqrt(area)
  nu = 0.01
  theta = 2*area*nu
  K = simulation_data[i, ]$K
  estimated_sp_rich[[i]] <- chisholm_model(area, theta, m0, K)
}

#get migration rates for plotting
migration <- as.vector(simulation_data$m)

#bind results to single dataframe
simulation_data_and_estimation <- cbind.data.frame(migration, simulation_data$sp_rich, round(estimated_sp_rich, digits=2))
names(simulation_data_and_estimation) <- c("Migration", "SimRich", "ModelRich")
#plot sim results and estimated results
p = ggplot() +
  geom_point(data = simulation_data_and_estimation, aes(x = migration, y = simulation_data$sp_rich), color = "blue") +
  geom_point(data = simulation_data_and_estimation, aes(x = migration, y = round(estimated_sp_rich, digits=2)), color = "red") +
  xlab('Migration Rate') +
  ylab('Species Richness')

print(p)

mean_data <- simulation_data_and_estimation[2001:2020, ]
names(mean_data) <- c("Migration_rates", "Mean_sim_results", "Est_Species_richness")
write.csv(mean_data, "../../Results/Non_NllsSimFit.csv", row.names = FALSE)
